import React from "react";
import {
    CloudRain,
    Flame,
    Waves,
    Bug,
    Volume2,
} from "lucide-react";

export const SHOP_ITEMS = [
    // 🐶 PETS
    {
        id: "pet_cat",
        category: "pet",
        name: "Mochi",
        icon: "🐱",
        price: 0,
        color: "#fcd34d",
        secondary: "#fff",
        blush: "#fda4af",
        desc: "แมวส้มพุงย้อย",
    },
    {
        id: "pet_dog",
        category: "pet",
        name: "Latte",
        icon: "🐕",
        price: 0,
        color: "#e7e5e4",
        secondary: "#d6d3d1",
        blush: "#fca5a5",
        desc: "ชิบะยิ้มหวาน",
    },
    {
        id: "pet_duck",
        category: "pet",
        name: "Duckie",
        icon: "🦆",
        price: 150,
        color: "#fef08a",
        secondary: "#f97316",
        blush: "#fca5a5",
        desc: "เป็ดน้อยปากเจ่อ",
    },
    {
        id: "pet_bunny",
        category: "pet",
        name: "Bunny",
        icon: "🐰",
        price: 300,
        color: "#fce7f3",
        secondary: "#fff",
        blush: "#f9a8d4",
        desc: "กระต่ายหูตั้ง",
    },
    {
        id: "pet_pig",
        category: "pet",
        name: "Babe",
        icon: "🐷",
        price: 500,
        color: "#fbcfe8",
        secondary: "#f472b6",
        blush: "#fb7185",
        desc: "หมูชมพู",
    },

    // 🏠 ROOMS
    {
        id: "theme_day",
        category: "room",
        name: "Daylight",
        icon: "☁️",
        price: 0,
        bgTop: "#e0f2fe",
        bgBot: "#f0f9ff",
        wall: "#fff",
        floor: "#f3f4f6",
        accent: "#bae6fd",
        shadow: "#cbd5e1",
        windowSky: "#7dd3fc",
        lightColor: "rgba(255, 255, 255, 0.3)",
        text: "slate-600",
        desc: "ห้องโทนฟ้าสว่าง",
    },
    {
        id: "theme_cozy",
        category: "room",
        name: "Warm Sunset",
        icon: "🌇",
        price: 0,
        bgTop: "#ffedd5",
        bgBot: "#fff7ed",
        wall: "#fffaf0",
        floor: "#fed7aa",
        accent: "#fdba74",
        shadow: "#e2e8f0",
        windowSky: "#fb923c",
        lightColor: "rgba(255, 237, 213, 0.2)",
        text: "orange-900",
        desc: "แสงเย็นอบอุ่น",
    },
    {
        id: "theme_night",
        category: "room",
        name: "Starlight",
        icon: "✨",
        price: 800,
        bgTop: "#312e81",
        bgBot: "#4338ca",
        wall: "#1e1b4b",
        floor: "#374151",
        accent: "#6366f1",
        shadow: "#111827",
        windowSky: "#0f172a",
        lightColor: "rgba(30, 27, 75, 0.5)",
        text: "indigo-100",
        desc: "กลางคืนเงียบสงบ",
    },
    {
        id: "theme_garden",
        category: "room",
        name: "Garden",
        icon: "🌻",
        price: 500,
        type: "outdoor",
        bgTop: "#7dd3fc", // Sky
        bgBot: "#bae6fd",
        wall: "#7dd3fc", // Sky
        floor: "#86efac", // Grass
        accent: "#4ade80",
        shadow: "#166534",
        windowSky: "#7dd3fc",
        lightColor: "rgba(255, 255, 255, 0.4)",
        text: "green-900",
        desc: "สวนหลังบ้านสดชื่น",
    },
    {
        id: "theme_park",
        category: "room",
        name: "Park",
        icon: "🌳",
        price: 600,
        type: "outdoor",
        bgTop: "#38bdf8", // Deeper Sky
        bgBot: "#7dd3fc",
        wall: "#38bdf8",
        floor: "#a3e635", // Lime Grass
        accent: "#65a30d",
        shadow: "#3f6212",
        windowSky: "#38bdf8",
        lightColor: "rgba(255, 255, 255, 0.3)",
        text: "green-900",
        desc: "สวนสาธารณะร่มรื่น",
    },
    {
        id: "theme_kitchen",
        category: "room",
        name: "Kitchen",
        icon: "🍳",
        price: 400,
        type: "indoor",
        bgTop: "#fef9c3",
        bgBot: "#fef08a",
        wall: "#fefce8",
        floor: "#e5e7eb", // Tiled
        accent: "#fde047",
        shadow: "#d1d5db",
        windowSky: "#7dd3fc",
        lightColor: "rgba(255, 255, 255, 0.3)",
        text: "yellow-900",
        desc: "ห้องครัวอบอุ่น",
    },
    {
        id: "theme_bedroom",
        category: "room",
        name: "Bedroom",
        icon: "🛏️",
        price: 450,
        type: "indoor",
        bgTop: "#fce7f3",
        bgBot: "#fbcfe8",
        wall: "#fff1f2",
        floor: "#fecdd3",
        accent: "#f472b6",
        shadow: "#fb7185",
        windowSky: "#7dd3fc",
        lightColor: "rgba(255, 255, 255, 0.2)",
        text: "pink-900",
        desc: "ห้องนอนสีชมพู",
    },
    {
        id: "theme_cafe",
        category: "room",
        name: "Cafe",
        icon: "☕",
        price: 700,
        type: "indoor",
        bgTop: "#e7e5e4",
        bgBot: "#d6d3d1",
        wall: "#f5f5f4",
        floor: "#a8a29e", // Wood
        accent: "#78716c",
        shadow: "#57534e",
        windowSky: "#7dd3fc",
        lightColor: "rgba(255, 255, 255, 0.2)",
        text: "stone-800",
        desc: "คาเฟ่สไตล์มินิมอล",
    },
    {
        id: "theme_boho",
        category: "room",
        name: "Boho Bedroom",
        icon: "🍂",
        price: 1000,
        type: "indoor",
        bgTop: "#e3d5ca", // Soft Taupe
        bgBot: "#d6ccc2",
        wall: "#eddede", // Pale Pinkish Beige
        floor: "#f5ebe0", // Light Wood
        accent: "#d4a373", // Rattan
        shadow: "#cbb8a9",
        windowSky: "#7dd3fc",
        lightColor: "rgba(255, 248, 240, 0.3)",
        text: "stone-600",
        desc: "ห้องนอนสไตล์โบฮีเมียน",
    },

    // 🎵 SOUNDS
    {
        id: "sound_rain",
        category: "sound",
        name: "Rain",
        icon: <CloudRain size={24} />,
        price: 0,
        desc: "เสียงฝนตก",
    },
    {
        id: "sound_fire",
        category: "sound",
        name: "Fire",
        icon: <Flame size={24} />,
        price: 0,
        desc: "เสียงกองไฟ",
    },
    {
        id: "sound_waves",
        category: "sound",
        name: "Ocean",
        icon: <Waves size={24} />,
        price: 0,
        desc: "เสียงคลื่น",
    },
    {
        id: "sound_night",
        category: "sound",
        name: "Crickets",
        icon: <Bug size={24} />,
        price: 200,
        desc: "เสียงแมลง",
    },
    {
        id: "sound_white",
        category: "sound",
        name: "Focus",
        icon: <Volume2 size={24} />,
        price: 200,
        desc: "White Noise",
    },
];

export const TIMER_MODES = {
    focus: { min: 25, label: "Focus" },
    short: { min: 5, label: "Short" },
    long: { min: 15, label: "Long" },
};
