import React from "react";
import {
    CloudRain,
    Flame,
    Waves,
    Bug,
    Volume2,
} from "lucide-react";

export const SHOP_ITEMS = [
    // 🐶 PETS
    {
        id: "pet_cat",
        category: "pet",
        name: "Mochi",
        icon: "🐱",
        price: 0,
        color: "#fcd34d",
        secondary: "#fff",
        blush: "#fda4af",
        desc: "แมวส้มพุงย้อย",
    },
    {
        id: "pet_dog",
        category: "pet",
        name: "Latte",
        icon: "🐕",
        price: 0,
        color: "#e7e5e4",
        secondary: "#d6d3d1",
        blush: "#fca5a5",
        desc: "ชิบะยิ้มหวาน",
    },
    {
        id: "pet_duck",
        category: "pet",
        name: "Duckie",
        icon: "🦆",
        price: 150,
        color: "#fef08a",
        secondary: "#f97316",
        blush: "#fca5a5",
        desc: "เป็ดน้อยปากเจ่อ",
    },
    {
        id: "pet_bunny",
        category: "pet",
        name: "Bunny",
        icon: "🐰",
        price: 300,
        color: "#fce7f3",
        secondary: "#fff",
        blush: "#f9a8d4",
        desc: "กระต่ายหูตั้ง",
    },
    {
        id: "pet_pig",
        category: "pet",
        name: "Babe",
        icon: "🐷",
        price: 500,
        color: "#fbcfe8",
        secondary: "#f472b6",
        blush: "#fb7185",
        desc: "หมูชมพู",
    },

    // 🏠 ROOMS
    {
        id: "theme_day",
        category: "room",
        name: "Daylight",
        icon: "☁️",
        price: 0,
        bgTop: "#e0f2fe",
        bgBot: "#f0f9ff",
        wall: "#fff",
        floor: "#f3f4f6",
        accent: "#bae6fd",
        shadow: "#cbd5e1",
        windowSky: "#7dd3fc",
        lightColor: "rgba(255, 255, 255, 0.3)",
        text: "slate-600",
        desc: "ห้องโทนฟ้าสว่าง",
    },
    {
        id: "theme_cozy",
        category: "room",
        name: "Warm Sunset",
        icon: "🌇",
        price: 0,
        bgTop: "#ffedd5",
        bgBot: "#fff7ed",
        wall: "#fffaf0",
        floor: "#fed7aa",
        accent: "#fdba74",
        shadow: "#e2e8f0",
        windowSky: "#fb923c",
        lightColor: "rgba(255, 237, 213, 0.2)",
        text: "orange-900",
        desc: "แสงเย็นอบอุ่น",
    },
    {
        id: "theme_night",
        category: "room",
        name: "Starlight",
        icon: "✨",
        price: 800,
        bgTop: "#312e81",
        bgBot: "#4338ca",
        wall: "#1e1b4b",
        floor: "#374151",
        accent: "#6366f1",
        shadow: "#111827",
        windowSky: "#0f172a",
        lightColor: "rgba(30, 27, 75, 0.5)",
        text: "indigo-100",
        desc: "กลางคืนเงียบสงบ",
    },

    // 🎵 SOUNDS
    {
        id: "sound_rain",
        category: "sound",
        name: "Rain",
        icon: <CloudRain size={24} />,
        price: 0,
        desc: "เสียงฝนตก",
    },
    {
        id: "sound_fire",
        category: "sound",
        name: "Fire",
        icon: <Flame size={24} />,
        price: 0,
        desc: "เสียงกองไฟ",
    },
    {
        id: "sound_waves",
        category: "sound",
        name: "Ocean",
        icon: <Waves size={24} />,
        price: 0,
        desc: "เสียงคลื่น",
    },
    {
        id: "sound_night",
        category: "sound",
        name: "Crickets",
        icon: <Bug size={24} />,
        price: 200,
        desc: "เสียงแมลง",
    },
    {
        id: "sound_white",
        category: "sound",
        name: "Focus",
        icon: <Volume2 size={24} />,
        price: 200,
        desc: "White Noise",
    },
];

export const TIMER_MODES = {
    focus: { min: 25, label: "Focus" },
    short: { min: 5, label: "Short" },
    long: { min: 15, label: "Long" },
};
